### ISSUE TITLE
API Field missing

### ISSUE THREAD

**Issue by mlapaglia** [bitpay/woocommerce-plugin#57]
The API Field on the settings is missing, not allowing me to insert the bitpay api key.

I get
    06-22-2015 @ 11:25:34 - BitPay Woocommerce payment plugin object constructor called. Plugin is v2.2.7 and server is PHP v5.4
06-22-2015 @ 11:25:34 -     [Info] $this->api_key            = 
06-22-2015 @ 11:25:34 -     [Info] $this->api_pub            = 
06-22-2015 @ 11:25:34 -     [Info] $this->api_sin            = 
06-22-2015 @ 11:25:34 -     [Info] $this->api_token          = 
06-22-2015 @ 11:25:34 -     [Info] $this->api_token_label    = 
06-22-2015 @ 11:25:34 -     [Info] $this->api_network        = 
06-22-2015 @ 11:25:34 -     [Error] The API Key was NOT an instance of PrivateKey!  Instead, it appears to be a NULL value.
06-22-2015 @ 11:25:34 -     [Error] The Public Key was NOT an instance of PublicKey!  Instead, it appears to be a NULL value.
06-22-2015 @ 11:25:34 -     [Error] The API Token was NOT an instance of Token!  Instead, it appears to be a NULL value.
06-22-2015 @ 11:25:34 -     [Info] Transaction speed is now set to: high
06-22-2015 @ 11:25:34 -     [Info] The plugin is NOT valid for use!
06-22-2015 @ 11:25:34 -     [Info] Entered generate_api_token_html()...
06-22-2015 @ 11:25:34 -     [Info] Leaving generate_api_token_html()...
06-22-2015 @ 11:25:34 -     [Info] Entered generate_order_states_html()...
06-22-2015 @ 11:25:34 -     [Info] Leaving generate_order_states_html()...

**Comment by sambohler** [comment]
Check the permissions of the templates/pairing.tpl and templates/token.tpl.  If you are unable to see the API Token HTML that allows you to pair, that is generally what causes it.  They have to be accessible from the web (eg yoursite.com/wp-content/plugins/bitpay-for-woocommerce/templates/pairing.tpl resolves to the template file and doesn't return a Forbidden page)

**Comment by travoc** [comment]
Any other thoughts on this? I'm getting the same errors. I have checked the templates and they are accessible.

**Comment by brianwang9100** [comment]
Hey @travoc, can you tell me what version of woocommerce and the bitpay plugin you are using?

**Comment by travoc** [comment]
Here you go:

WC Version:		2.3.13
WC Database Version:		2.3.13
WP Version:		4.2.4
WP Memory Limit:		64 MB
Language:		en_US
Server Info:		Apache
PHP Version:		5.4.43
PHP Post Max Size:		8 MB
PHP Time Limit:		60
PHP Max Input Vars:		1000
SUHOSIN Installed:		-
MySQL Version:		5.5.44
Max Upload Size:		8 MB
Active Plugins (16)
Akismet	 	by Automattic 3.1.3
BitPay for WooCommerce	 	by bitpay 2.2.7
Contact Form 7	 	by Takayuki Miyoshi 4.2.2
Envato WordPress Toolkit	 	by Envato 1.7.3
Google Analytics by Yoast	 	by Team Yoast 5.4.5
Google XML Sitemaps	 	by Arne Brachhold 4.0.8
Hide Title	 	by Brandon Kraft & Randall Runnels 1.0.4
WPBakery Visual Composer	 	by Michael M - WPBakery.com 4.6
MailChimp	 	by MailChimp and Crowd Favorite 1.4.2
Regenerate Thumbnails	 	by Viper007Bond 2.2.4
Revolution Slider	 	by ThemePunch 4.6.93
WooCommerce Header Category Image	 	by Get Bowtied 1.0.0
WooCommerce Product SKU Generator	 	by SkyVerge 1.2.2
WooCommerce	 	by WooThemes 2.3.13
WordPress Importer	 	by wordpressdotorg 0.6.1
WP-Lister Pro for eBay	 	by Matthias Krok 2.0.9.7

**Comment by brianwang9100** [comment]
I installed a fresh new copy of Word Press 4.2.4, WooCommerce 2.3.13, Bitpay plugin 2.2.7 on my server and I had no issues with having the Pairing code field to show up, with the template files ownership set to root:root and permissions set to 0644/-rw-r--r-- on the template files. Do you think you could screenshot the settings page (so I can see what you're talking about specifically) and tell me what your ownership and permissions look like on the template files (pairing.tpl, token.tpl)?

**Comment by brianwang9100** [comment]
Actually your issue may lie in the templates folder itself. Please let me know what the permissions are on that. I believe that the template folder has to have executable permissions. (chmod 0755 templates -R should fix this problem for sure)

**Comment by travoc** [comment]
I set the folder to 755 and the files to 644 but I'm still having the same issue. When I submit the token on the settings interface, the dots spin indefinitely and the error above appears in the Bitpay log.

drwxr-xr-x  2 swish psacln  4096 Jul 31 08:49 templates

-rw-r--r-- 1 swish psacln  583 Jul 31 08:49 pairing.tpl
-rw-r--r-- 1 swish psacln  482 Jul 31 08:49 token.tpl

I also chowned the files and folder to root:root and it did not make a difference.

drwxr-xr-x  2 root          root    4096 Jul 31 08:49 templates

-rw-r--r-- 1 root          root    583 Jul 31 08:49 pairing.tpl
-rw-r--r-- 1 root          root    482 Jul 31 08:49 token.tpl

**Comment by brianwang9100** [comment]
Since you can see the pairing code field, I don't believe the problem is with permissions or ownership. You might want to double check your network and API Pairing code. Remember this particular plugin requires a pairing code, not a legacy api key. If the key you are using is more than 8 characters, then you're using the wrong key and submitting it will return similar log errors as above. If you're using a livenet pairing code with the testnet network selected or vice versa, then the plugin will return similar log errors as above. Finally, if you created the token with "require authentication" unchecked, you will not get a pairing code but instead a token, which is not what you want and authentication will fail. What does confuse me is that the dots spin indefinitely which may be an authentication problem. If you were really using a wrong API Key, there should have been a popup that tells you that api authentication failed. 

If this still doesn't work, try contacting support@bitpay.com and reexplain the problem and we'll see if we can get this sorted out there.

**Comment by aleitner** [comment]
@travoc, we may have found the source of the issue. in bitpay-for-woocommerce/class-wc-gateway-bitpay.php, there are two lines of code that may be causing the issue. On lines 337 and 338, change:

```
$pairing_form = file_get_contents(plugin_dir_url(__FILE__).'templates/pairing.tpl');
$token_format = file_get_contents(plugin_dir_url(__FILE__).'templates/token.tpl');

```
to:
```
$pairing_form = file_get_contents(dirname(__FILE__) . '/templates/pairing.tpl');
$token_format = file_get_contents(dirname(__FILE__) . '/templates/token.tpl');
```

Let us know if that works for you. If it does, we'll push a new release.

**Comment by travoc** [comment]
I made the change but I'm still having the same problem and seeing the same errors.

![image](https://cloud.githubusercontent.com/assets/9854034/9228282/af681c14-40cc-11e5-9c2b-97befa84c71e.png)

**Comment by aleitner** [comment]
@travoc, so the error that you are getting can occur from a couple things that I know of.
If you are inputing an "API KEY" into the pairing field, you will get this error.
If you put a test "PAIRING CODE" from test.bitpay.com into the pairing field and click pair with live, then you will get this error.
If you put a live "PAIRING CODE" from bitpay.com into the pairing field and click pair with test, then you will get this error.

Can you confirm that you are using a pairing code from bitpay.com and pushing submit with the 'live' setting?

Additionally can you provide any information contained in apache's error.log file?

**Comment by travoc** [comment]
I was checking the wrong apache error log when I first diagnosed this error. I did not realize that this product required php-mcrypt, but now I can see "PHP Fatal error:  Call to undefined function Bitpay\\Crypto\\mcrypt_module_open()" in the logs.

I installed php-mcrypt on the server and I was able to validate the API token on Livenet.

Thank you for your time.

**Comment by aleitner** [comment]
@travoc Glad you were able to figure it out! Our woocommerce plugin has a check for if mcrypt is installed, and this should have given you an error when trying to install our plugin thus preventing it from even being installed. Did you install the plugin on a staging server, and then migrate it to production? If so then the staging server may have had mcrypt installed, and the production server didn't. This is the only way I can think of getting around the installation check.

**Comment by travoc** [comment]
The mcrypt check must not have worked. I likely added it from the "Add Plugins" page in Wordpress or I may have uploaded the zip file, but there's no way that it came over from another server.
