### ISSUE TITLE
Price must be formatted as a float

### ISSUE THREAD

**Issue by gajdi8** [bitpay/woocommerce-plugin#78]
I'm getting this error message until I set up 1 or 2 decimals in Woocomerce Settings.
The problem is, the currency I'm using (Hungarian Forint) has no smaller unit so it's very disturbing.
Is there any workaround for this?

**Comment by pieterpoorthuis** [comment]
solved in release 2.2.13

**Comment by mdbootstrap** [comment]
When 2.2.13 will be available for WordPress ? Currently the newest available is 2.2.12 which still have the issue.

**Comment by pieterpoorthuis** [comment]
Working on a WC v2.6 backwards compatibility fix. When that's in place we'll publish at wordpress.org.

**Comment by mdbootstrap** [comment]
Thanks, any ETA? (I know that it's always difficult question, we are developers too) however if you could estimate whether it's matter of days / weeks or months would be really helpfull to plan our work.

**Comment by pieterpoorthuis** [comment]
Aiming to publish end of next week at wordpress.org

**Comment by mdbootstrap** [comment]
BTW - I've just manually downloaded 2.2.13 from github , installed as a zip and unfortunately I found that this issue still persist :( I got it from here: https://github.com/bitpay/woocommerce-plugin/releases

**Comment by toleabivol** [comment]
I can also confirm that downloading 2.2.13 from github gives the same error

**Comment by NicolasDorier** [comment]
Fix at php client level https://github.com/btcpayserver/php-bitpay-client/commit/27146f02499bfa4924744b5c8c771107d4b06ba3 on my fork a while ago

**Comment by mdbootstrap** [comment]
@NicolasDorier after your fix I am getting error on checkout: 

> Sorry, but Bitcoin checkout with BitPay does not appear to be working.

Any thoughts how to debug that?

**Comment by NicolasDorier** [comment]
@mdbootstrap not sure it fix your issue, but also try that on the plugin https://github.com/btcpayserver/woocommerce-plugin/commit/9a13c117116e439d33098a990bf3c8ab54a5f54e

**Comment by mdbootstrap** [comment]
@NicolasDorier thanks, I've found it in debug logs - the minimum amount cannot be < 5$.

**Comment by pieterpoorthuis** [comment]
thanks for the PHP fix, I've merged it. One we have the WC 2.6 backwards compatible code in place we'll release a new WooCommerce BitPay plugin
